### ISSUE TITLE
Hello, may I ask if you can provide a trained model？

### ISSUE THREAD

**Issue by hhy150** [DAMO-NLP-SG/IE-E2H#2]

**Comment by gao-xiao-bai** [comment]
Hi, we do not provide the trained model checkpoints. However, you can easily train the models yourself using the scripts and configuration files we provide.

**Comment by hhy150** [comment]
Okay, thank you. We will train ourselves. The main issue is that our laboratory's cards are a bit scarce. I originally wanted to try reasoning directly to see the effect, so I came to ask. Thank you for your reply.
